---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Create kolla temporary directory
  file:
    path: "{{ kolla_tmpdir }}"
    state: "directory"
    recurse: "yes"

- name: Create kolla log directory
  file:
    path: "{{ kolla_logs_dir }}"
    state: "directory"
    recurse: "yes"

- block:
    - name: Install python-setuptools and git
      vars:
        packages:
          - python-setuptools
          - git
      package:
        name: "{{ packages }}"
        state: "present"

    - name: Install pip
      easy_install:
        name: "pip"
        state: "present"

    - name: Install tox
      pip:
        name: "tox"
        state: "present"

    - name: Retrieve Kolla
      git:
        repo: "{{ kolla_repository }}"
        dest: "{{ kolla_tmpdir }}"
        version: "{{ kolla_git_version }}"
        force: "yes"

    - name: Retrieve Kolla version
      command: git rev-parse HEAD
      args:
        chdir: "{{ kolla_tmpdir }}"
      register: kolla_version

    - name: Generate Kolla virtual environment with tox
      command: tox -e build-centos-binary --notest
      args:
        chdir: "{{ kolla_tmpdir }}"

    - name: Set kolla-build location
      set_fact:
        kolla_build_path: "{{ kolla_virtualenv }}/bin/kolla-build"

  when: kolla_setup_method == "source"

- block:
    - name: Install kolla, tripleo-common-containers, python-tripleoclient from packages
      vars:
        packages:
          - openstack-kolla
          - openstack-tripleo-common-containers
          - python-tripleoclient
      package:
        name: "{{ packages }}"
        state: "present"

    - name: Retrieve Kolla version
      command: rpm -q openstack-kolla --qf "%{VERSION}-%{RELEASE}"
      register: kolla_version

    - name: Set kolla-build location
      set_fact:
        kolla_build_path: "kolla-build"

  when: kolla_setup_method == "binary"

- name: Detect invalid kolla_setup_method
  fail:
    msg: "Kolla setup method must be 'source' or 'binary'"
  when: kolla_setup_method != "source" and kolla_setup_method != "binary"

# These tasks parse the output from the prepare call to build a full list of
# images to build. It is the default if kolla_rdo_images is not set.
# It boils down to
# - Removing the prefix "imagename: x/x-" and suffix "-x:x" from all entries
# - Store the list value within container_images
- name: Generate container image yaml
  shell: >
    openstack overcloud container image prepare \
      --namespace x --prefix x --suffix x --tag x | \
      sed -e 's/imagename: x\/x-//' -e 's/-x:x//'
  register: supported_containers

- name: Parse supported containers
  set_fact:
    containers: "{{ supported_containers.stdout | from_yaml }}"

- name: Save parsed containers
  set_fact:
    tripleo_default_images: "{{ containers.container_images }}"

- name: Generate image build_id
  set_fact:
    build_id: "{{ lookup('pipe', 'date +%s') }}"
  when: build_id is not defined

- name: Set Kolla build profile
  set_fact:
    build_profile: >
      {% if kolla_rdo_images is defined and kolla_rdo_images -%}
      {% set profile = "tripleo_custom" -%}
      {% else -%}
      {% set profile = "tripleo_default" -%}
      {% endif -%}
      {{- profile -}}

- name: Set up kolla-build.conf
  template:
    src: "kolla-build.conf.j2"
    dest: "{{ kolla_tmpdir }}/kolla-build.conf"

- name: Set up template-overrides.j2
  template:
    src: "template-overrides.j2"
    dest: "{{ kolla_tmpdir }}/template-overrides.j2"

